### ISSUE TITLE
Unable to Geneterate Scalatra App using g8

### ISSUE THREAD

**Issue by seasonedgeek** [scalatra/scalatra.g8#40]
I am interested in a new Manning book on "Scalatra in Action", and I thought I would try to generate a scalatra app using g8 scalatra/scalatra-sbt via terminal before purchasing the book.  My attempt failed, resulting in an error reported during sbt execution: java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.writeStringToFile.

I have installed the following on Mac Yosemite:
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)
Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode) 
conscript 2.9.2
g8 0.6.6
scala 2.11.1 
sbt 0.13.5 
scalatra 2.3.0 

My PATH is set correctly.

Please see https://gist.github.com/seasonedgeek/8b3716e7e2a22e3822bd for stack trace.

Did I miss anything? Additional instructions/suggestions welcomed. Thanks.

**Comment by magnolia-k** [comment]
@seasonedgeek 

Can I close this issue any longer?

**Comment by seasonedgeek** [comment]
Yes, please close the issue.

**Comment by magnolia-k** [comment]
thanks!
