### ISSUE TITLE
rename it to scalatra-seed.g8 or scalatra.g8

### ISSUE THREAD

**Issue by magnolia-k** [scalatra/scalatra.g8#76]
https://github.com/foundweekends/giter8/wiki/giter8-templates

As a reference to other templates, 'sbt' seems to be unnecessary

**Comment by takezoe** [comment]
Agree with you. I think it comes from scalatra-sbt plugin. `scalatra.g8` seems like good.

**Comment by magnolia-k** [comment]
https://github.com/scalatra/scalatra-sbt.g8/pull/77

**Comment by takezoe** [comment]
I merged #77 and renamed repository. Also updated https://github.com/foundweekends/giter8/wiki/giter8-templates.

**Comment by takezoe** [comment]
@magnolia-k In addition, I created a pull request to fix the document. Could you check it? https://github.com/scalatra/scalatra-website/pull/151

That's all things to do for this issue, right?
