### ISSUE TITLE
Can't init project with SBT.

### ISSUE THREAD

**Issue by gabriel-card** [scalatra/scalatra.g8#88]
I believe it's a problem with a dependency.

> [error] Caused by: com.jcraft.jsch.JSchException: Algorithm negotiation fail
[error] 	at com.jcraft.jsch.Session.receive_kexinit(Session.java:550)
[error] 	at com.jcraft.jsch.Session.connect(Session.java:297)
[error] 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
[error] 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
[error] 	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
[error] 	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
[error] 	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
[error] 	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
[error] 	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
[error] 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
[error] 	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
[error] 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
[error] 	at giter8.JgitHelper$.clone(JgitHelper.scala:116)
[error] 	at giter8.JgitHelper$.run(JgitHelper.scala:67)
[error] 	at giter8.Giter8.$anonfun$run$2(giter8.scala:34)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at giter8.Giter8.run(giter8.scala:33)
[error] 	at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:31)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.TemplateCommandUtil$.call(TemplateCommand.scala:100)
[error] 	at sbt.TemplateCommandUtil$.runTemplate(TemplateCommand.scala:78)
[error] 	at sbt.TemplateCommandUtil$.$anonfun$run$1(TemplateCommand.scala:58)
[error] 	at sbt.TemplateCommandUtil$.$anonfun$run$1$adapted(TemplateCommand.scala:54)
[error] 	at scala.collection.LinearSeqOptimized.find(LinearSeqOptimized.scala:111)
[error] 	at scala.collection.LinearSeqOptimized.find$(LinearSeqOptimized.scala:108)
[error] 	at scala.collection.immutable.List.find(List.scala:86)
[error] 	at sbt.TemplateCommandUtil$.run(TemplateCommand.scala:54)
[error] 	at sbt.TemplateCommandUtil$.runTemplate(TemplateCommand.scala:41)
[error] 	at sbt.TemplateCommandUtil$.$anonfun$templateCommand$2(TemplateCommand.scala:24)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] org.eclipse.jgit.api.errors.TransportException: git@github.com:scalatra/scalatra.g8.git: Algorithm negotiation fail

**Comment by magnolia-k** [comment]
I do not reproduce it in my own environment, but can you tell me the version of OS and sbt too?

Also, is another giter 8 template successful? Have you tried deleting the target directory?

**Comment by AndersonChoi** [comment]
Hi @gabriel-bezerra .
I want to know next things to solve your problem.
## steps
## problem
## expectation
## sbt version
Thank you.

**Comment by gabriel-bezerra** [comment]
Sorry, @AndersonChoi, did you mean to mention @gabriel-card instead?

**Comment by gabriel-card** [comment]
Hi guys, i don't remember now but I think it was a problem with my own sbt setup. I remember fixing it, but sadly don't remember how.
I'll be closing the issue!
